spring:
  kafka:
    consumer:
      bootstrap-servers: #
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate # 수동으로 커밋하겠다.
      type: single # 하나씩 vs 여러개

  session:
    store-type: jdbc

  h2:
    console:
      enabled: true

  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa

