spring:
  config:
    activate:
      on-profile: local

  kafka:
    consumer:
      bootstrap-servers: ${kafka-ip}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      listener:
        ack-mode: manual_immediate # ???? ?????.
        type: single # ??? vs ???

server:
  port: 8082

logging:
  file:
    name: server2.log
    path: .

