spring:
  config:
    activate:
      on-profile: local

  kafka:
    producer:
      bootstrap-servers: 54.180.171.233:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true

server:
  port: 8081

logging:
  file:
    name: server1.log
    path: .